# Generated by Django 4.1.1 on 2022-09-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_bio_profile_id_user_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id_user',
            field=models.IntegerField(blank=True),
        ),
    ]
