# Generated by Django 4.1.1 on 2022-09-29 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_commentpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentpost',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='commentpost',
            name='username',
        ),
    ]
