# Generated by Django 4.1.1 on 2022-09-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_commentpost_post_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentpost',
            name='comment',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
